### ISSUE TITLE
add func to  return

### ISSUE THREAD

**Issue by justLlz** [miguelgrinberg/microdot#11]
![2EE19C19-C447-4d62-940A-67A460A27C4C](https://user-images.githubusercontent.com/42207999/84746570-bdcfb100-afe8-11ea-9fc0-d5e1076ed3eb.png)
    @classmethod
    def send(cls, file_date, content_type=None, status_code=200):
        if not content_type:
            content_type = 'application/octet-stream'
        return cls(body=file_date, status_code=status_code,
                   headers={'Content-Type': content_type})

**Comment by miguelgrinberg** [comment]
Why is this necessary? It is a single line of code to return some data:

```
    return file_data, 200, {'Content-Type': 'application/octet-stream'}
```
