### ISSUE TITLE
unable to install microdot on esp8266

### ISSUE THREAD

**Issue by ghouse41** [miguelgrinberg/microdot#13]
>>> import upip
>>> upip.install('microdot')
Installing to: /lib/
Warning: micropython.org SSL certificate is not validated
Error installing 'microdot': syntax error in JSON, packages may be partially installed
>>>

**Comment by miguelgrinberg** [comment]
The upip is not very robust. Sometimes it reads partial information from the package repository, making it think the data is invalid, other times it just runs out of memory. I suggest you just get the .py file(s) that you are interested in from this repository and copy them into your project.

**Comment by ghouse41** [comment]
Thank you, after copying microdot.py able to run server. Thank you for your quick  response.
