### ISSUE TITLE
Int type in a url pattern does not handle negative numbers

### ISSUE THREAD

**Issue by dannystaple** [miguelgrinberg/microdot#137]
**Describe the bug**
A negative number is not matched by the int type in a url pattern.

**To Reproduce**
1. Create a url pattern like `@app.route('/set_servo/<int:position>`
2. Send a value like `/set/servo/-30` (to move the servo 30 degrees anti clockwise from neutral)
3. You will receive a 404 as the pattern will not be matched.

**Expected behavior**
The function attached to the url pattern would receive the argument position=-30.

**Additional context**
Note that the unit tests only verify positive integer numbers too.

**Comment by miguelgrinberg** [comment]
Oh, wow, what an oversight. I'll take care of this!

**Comment by miguelgrinberg** [comment]
The fix is in release 1.3.1.
