### ISSUE TITLE
Please provide a port to CircuitPython

### ISSUE THREAD

**Issue by adrianblakey** [miguelgrinberg/microdot#155]
**Describe the solution you'd like**
The adafruit http server does not support websockets. Seems like this does - hence, please could you port it?

**Describe alternatives you've considered**
adafruit http server.

**Comment by miguelgrinberg** [comment]
What is the problem when you use Microdot with CircuitPython?

**Comment by miguelgrinberg** [comment]
If someone tests Microdot with CircuitPython and finds any issues I'll be happy to look at them.
