### ISSUE TITLE
WebSocket die and after a time HTTP die as well

### ISSUE THREAD

**Issue by beyonlo** [miguelgrinberg/microdot#156]
Hello @miguelgrinberg 

I'm using ESP32-S3 with MicroPython 1.20, and I have a strange behaviour in rare times using websocket when I'm connecting from the browser (using your Websocket example) to ESP32-S3 just via SoftAP.

ESP32-S3 (SoftAP) 192.168.4.1 --- Notebook/SmartPhone (Android/IOS) (chrome/safari/firefox) running `Microdot WebSocket Demo`

When I put the IP 192.158.4.1 on the browser, shows the text edit, so I put the data and I press enter, but I have no feedback from echo. Shows no errors on console, and to back to works I need to reset the ESP32-S3.

There is some possibilities: bug on ESP32-S3 SoftAP, or MicroPython SoftAP causing incompatibility (in rare cases) with other clients, or can be a Microdot/WebSocket problem? 

Unfortunately I can't find a way to reproduce this problem, it happens some times. If you have any idea to me investigate, like as a extra code for debug, etc, or maybe you think to add a extra code to manage this problem, I appreciate.

Thank you!

**Comment by miguelgrinberg** [comment]
Can you look in the browser's console or network tab to see how the websocket connection appears there?
