### ISSUE TITLE
Unhandled EINTR exception thrown from Microdot.run() accept() call

### ISSUE THREAD

**Issue by amakaro** [miguelgrinberg/microdot#16]
Microdot 0.3.0 (running on MicroPython v1.12-1 on 2020-02-09; linux version on Ubuntu 20.04.2 LTS) does not handle OS Error 4 (EINTR) that can be thrown from the s.accept() call in Microdot.run().
[Symptom: Hit Reload repeatedly in web-browser to load one HTML file and one PNG image file; EINTR gets thrown (seemingly at random) approximately 1 time in 10]. 
Arguably this exception should be handled by Micropython. 

This page ( https://stackoverflow.com/questions/14136195/what-is-the-proper-way-to-handle-in-python-ioerror-errno-4-interrupted-syst ) suggests the EINTR can be ignored and the operation retried.

I am working around this issue by a change to Microdot.run() to ignore the exception as per attached file
[run.py.txt](https://github.com/miguelgrinberg/microdot/files/5924921/run.py.txt)
ws:

**Comment by miguelgrinberg** [comment]
Thanks! Looks like a good fix, I'll test it and add it to the package.

**Comment by miguelgrinberg** [comment]
@amakaro What version of MicroPython are you using? It appears this was fixed directly in the interpreter in the 1.14 release. The commit is here: https://github.com/micropython/micropython/commit/9418611c8aa860812e28b6e2b6bfde7be5817b43.

Given that this is now handled internally I don't see a need to patch it again here.

**Comment by amakaro** [comment]
Hi Miguel,

As per the original issue report, I was using Micropython 1.12. (“sudo apt install micropython” on Ubuntu 20.04).

 

I’ll have to see if I can get a 1.14 version installed on Ubuntu for dev purposes.

My target machine is an ESP32 and I see that a Micropython 1.14 build was released for the ESP32 only 3 days ago….

 

I agree that you do not need to patch; perhaps just document the dependency.

 

Adrian
