### ISSUE TITLE
Hang on python 3.10.4

### ISSUE THREAD

**Issue by sophiedegran** [miguelgrinberg/microdot#195]
Migrate from microdot 1.33 to 2.02
Use Microdot and Websocket package.
It seem to be an asyncio problem..
microdot.py line 25 in invoke handler
TypeError: BaseEventLoop.run_in_executor () got an unexpected keyword argument 'path'

The same code (with microdot 2.02) work perfectly well under micropython 1.21

Perharps the 2.x version is no more compatible directly with python?
I will try with python last release (3.12.x)

**Comment by miguelgrinberg** [comment]
This is actually a bug, I'll take care of it shortly.

**Comment by miguelgrinberg** [comment]
@sophiedegran Please upgrade to 2.0.3 for the fix.

**Comment by sophiedegran** [comment]
Thanks
I will continue testing under micropython
It seem more robust and reactiv

Take your time to appreciate 2024!
What you've done is amazing ☺

Le dim. 7 janv. 2024 11:56, Miguel Grinberg ***@***.***> a
écrit :
