### ISSUE TITLE
signal module doesnt exist in micropython

### ISSUE THREAD

**Issue by seandepagnier** [miguelgrinberg/microdot#211]
https://github.com/miguelgrinberg/microdot/blame/901f4e55b83cba4eb297e070ef159ff19d456059/src/microdot/wsgi.py#L3

I commented out this line and the line using signal and in my limited testing it seems to work.

**Comment by miguelgrinberg** [comment]
What is the point of using the WSGI module with micropython? That module only makes sense when using standard Python.

**Comment by seandepagnier** [comment]
I am not sure, I just wanted to use websockets and the examples used this module.

**Comment by miguelgrinberg** [comment]
@seandepagnier what examples are you running? Where from?

**Comment by seandepagnier** [comment]
Sorry,  I found another example now.
