### ISSUE TITLE
Integer-type dynamic path component does not match 0

### ISSUE THREAD

**Issue by kevin-pololu** [miguelgrinberg/microdot#212]
**Describe the bug**
An integer-type dynamic path component does not match the value 0.

**To Reproduce**
1. Define a route for a URL like `@app.route('/foo/<int:bar>')`
2. Request a URL like /foo/0
3. The response will be a 404

**Expected behavior**
The `<int:bar>` dynamic component should match the value 0.

**Additional context**
This appears similar to #137 but probably has a different cause. I think the problem is in [this check](https://github.com/miguelgrinberg/microdot/blob/901f4e55b83cba4eb297e070ef159ff19d456059/src/microdot/microdot.py#L865); I kind of suspect it isn't even necessary because you've already checked `if arg is None:` a few lines up, but I'm not sure.

Also, similar to what #137 pointed out, the unit tests don't seem to test a value of 0.

**Comment by miguelgrinberg** [comment]
Thanks, I'll take care of it.

**Comment by miguelgrinberg** [comment]
@kevin-pololu Can I ask you to retest using the main branch? Let me know if there are any remaining issues.

**Comment by kevin-pololu** [comment]
Seems good now. Thanks!
