### ISSUE TITLE
[BUG] WebSocket

### ISSUE THREAD

**Issue by MeghadeepRoyChowdhury** [miguelgrinberg/microdot#245]
**Describe the bug**
import statement in the websocket file says 
`from microdot import Request, Response`
But after fixing that (before fixing it, the code could not be frozen in a module), anytime I try to create a connection, it says:
```
Traceback (most recent call last):
  File "microdot/microdot.py", line 1330, in handle_request
  File "microdot/microdot.py", line 428, in create
  File "microdot/microdot.py", line 371, in __init__
ValueError: need more than 1 values to unpack
```
I'm using the `websocket_upgrade` function, but it gives the same ValueError (in different lines) if I use `with_websocket`

**Expected behaviour**
The import statement should say 
`from microdot.microdot import Request, Response`
and that WebSocket handshake should be successful

**Steps to reproduce**
The example for websockets in the API docs should suffice
```
@app.route('/echo')
async def echo(request):
    if not authenticate_user(request):
        abort(401)
    ws = await websocket_upgrade(request)
    while True:
        message = await ws.receive()
        await ws.send(message)
```

**Comment by miguelgrinberg** [comment]
The code is correct as it is. If the imports do not work for you it must be because you have not copied the `microdot/__init__.py` file to your project.

**Comment by MeghadeepRoyChowdhury** [comment]
You are right, I had indeed not included the _init_.py in my project my bad!

And yes, I also did not think that the import issue is related to the problem I'm facing, it's just the import issue was such an "easy fix", I did not bother creating two separate issues on GitHub.

This is my Insomnia log (includes everything I send to the server):
```
* Preparing request to wss://192.168.6.118/metrics
* Current time is 2024-07-22T11:50:11.575Z
* Using HTTP 1.1

> GET /metrics HTTP/1.1
> user-agent: insomnia/9.3.2
> x-api-key: 39650ncvrv9iz967d6a2e7k5n6mqzhw7
> cookie: null;
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Key: z2trjAVZrukFQjDiESxJKA==
> Connection: Upgrade
> Upgrade: websocket
> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
> Host: 192.168.6.118

< HTTP/1.0 400 N/A
< content-type: text/plain; charset=UTF-8
< content-length: 11

| Bad request

* Unexpected response 400
```

**Comment by miguelgrinberg** [comment]
Right. The `Cookie` header is invalid I believe. Is `null` the name of the cookie you want to send? It has no value.

**Comment by MeghadeepRoyChowdhury** [comment]
That's the default value that Insomnia shows when I do not add any cookies, it's not sending any cookie headers, sorry, I really should've been clearer about that.

Is there a Python library you recommend for trying to reproduce this in a different environment?

**Comment by miguelgrinberg** [comment]
> That's the default value that Insomnia shows when I do not add any cookies, it's not sending any cookie headers, sorry, I really should've been clearer about that.

That invalid cookie header is in fact being sent to the server and is causing Microdot's cookie parser to choke. Once you figure out how to remove it from your client requests the problem will disappear.

If you want to try a different client you can use Postman. Or if you prefer a Python-based client, then my simple-websocket library should do. [Here](https://github.com/miguelgrinberg/simple-websocket/blob/main/examples/echoclient.py) is an example.

**Comment by MeghadeepRoyChowdhury** [comment]
Thank you! That is what seems to be the problem, I went back to Postman (started using Insomnia when I found out that it is open-source), and the error disappeared. Thank you so much for the quick turnaround! I will open an issue on Insomnia's GitHub page! Apologies for taking your time out for no reason!

**Comment by MeghadeepRoyChowdhury** [comment]
Thank you! That is what seems to be the problem, I went back to Postman (started using Insomnia when I found out that it is open-source), and the error disappeared. Thank you so much for the quick turnaround! I will open an issue on Insomnia's GitHub page! Apologies for taking your time out for no reason!
