### ISSUE TITLE
uTemplate {% include %} causing 500 error

### ISSUE THREAD

**Issue by zyltr** [miguelgrinberg/microdot#262]
**Describe the bug**
When using `{% include "header.html %}` inside a template and `header.html` is empty, it causes the server to return a 500 error.

**index.html**

```
...
<body>
  <header>
      <!-- An Empty Template Causes uTemplate to Fail -->
      {% include "header.html" %}
  </header>
  <main>
      <h1>Hello world!</h1>
  </main>
</body>
...
```

**header.html**

```
```

**To Reproduce**
Using a Pi Pico W
1. Copy file contents to microcontroller
2. run main
3. Connect to Microcontroller Access Point (SSID "Pico W", Key "raspberry")
4. Load index.html by going to 192.168.4.1

**Additional context**

![500](https://github.com/user-attachments/assets/8b005b9e-ffe7-409c-987d-2365a382a80b)

**Source**

[uDot.zip](https://github.com/user-attachments/files/17626370/uDot.zip)

**Comment by miguelgrinberg** [comment]
uTemplate is a 3rd party project that is unrelated to Microdot. If you have found an issue with it you can submit a bug report on the project's repository at https://github.com/pfalcon/utemplate.
