### ISSUE TITLE
Access log of all requests and responses

### ISSUE THREAD

**Issue by pfctdayelise** [miguelgrinberg/microdot#30]
It would be helpful (especially during development) to be able to log requests and responses, similar to apache/nginx/uwsgi logs. Probably using Common Log Format would be handy.

**Comment by miguelgrinberg** [comment]
The `run()` method has a `debug` argument that you can set to `True` to log requests and responses. Documentation: https://microdot.readthedocs.io/en/latest/api.html#microdot.Microdot.run.

**Comment by pfctdayelise** [comment]
Thank you, somehow that escaped my attention.
