### ISSUE TITLE
Affinity for any particular templating library?

### ISSUE THREAD

**Issue by stevenbell** [miguelgrinberg/microdot#32]
Thanks for creating Microdot!  I teach an introductory engineering class with MicroPython and the ESP32, and Microdot's minimalism is perfect for me.

Do you have a suggested or preferred templating system for microdot?  (My experience is with Flask/Jinja, and I see that picoweb is designed to work with utemplate).  Or is part of the point that it'll work with whatever template system I want?

**Comment by miguelgrinberg** [comment]
Yeah, the idea is that you can use any templating system that you like, Microdot does not impose a choice on you. The utemplate engine should work well.
