### ISSUE TITLE
ESP32 "Connection Refused" by server

### ISSUE THREAD

**Issue by bhavesh-k** [miguelgrinberg/microdot#37]
Wrote a simple "hello world" server as shown in the example, but getting "Connection refused" error when trying to connect. I tried from multiple web browsers as well as using `curl` on the command line.

I am running on the Adafruit ESP32 ['Huzzah32'](https://www.adafruit.com/product/3405) board

Here is the code:

```
from neopixel import NeoPixel
from machine import Pin
import time
from microdot import Microdot

time.sleep(3)  # give 3 seconds to connect to WiFi

# web server
app = Microdot()

@app.route('/')
def hello(request):
    return 'Hello world'

print('Starting microdot app')
app.run()
```

Output of `curl`:
```
❯ curl http://192.168.1.198/
curl: (7) Failed to connect to 192.168.1.198 port 80: Connection refused
```

**Comment by miguelgrinberg** [comment]
The default port for the web server is 5000, not 80.
