### ISSUE TITLE
upip install of microdot-asyncio fails

### ISSUE THREAD

**Issue by xorbit** [miguelgrinberg/microdot#4]
Similar to #2, I get the same error for `microdot-asyncio` installing with `upip`.

```python
>>> upip.install('microdot-asyncio')
Installing to: /lib/
Error installing 'microdot-asyncio': , packages may be partially installed
```
Again no error message between : and ,
Same fix hopefully?

**Comment by miguelgrinberg** [comment]
yeah, forgot to fix this one as well. Should be okay now.
