### ISSUE TITLE
Feature request: Websocket support 

### ISSUE THREAD

**Issue by beyonlo** [miguelgrinberg/microdot#40]
Hello! 

As you [wrote here](https://github.com/miguelgrinberg/microdot/issues/39)  that are opened to suggestions for new features, I have just one that I consider very important: the Websocket support.

My goal is to create a simple web interface for the ESP32, STM32  to configure some sensors (like as temperature, humity, etc) and monitoring (events, alarms) it real time. Well, with Websocket I can just wait a event/alarms coming without  todo a polling on the HTTP Server.

In my opinion is a very important feature!

Thank you in advance!

**Comment by miguelgrinberg** [comment]
Duplicate of #34, also by yourself. Closing.

**Comment by beyonlo** [comment]
Hello @miguelgrinberg 

Ohh, I'm sorry, I forgot that I already did that. I was just looking for the opened issues, and that request was at he closed issues.

Please, if you in some moment think to start a Websocket support for the Microdot, let us to know :)

Thank you very much!
