### ISSUE TITLE
microdot serving over Ethernet rather than WiFi on ESP32

### ISSUE THREAD

**Issue by AndyThirtover** [miguelgrinberg/microdot#42]
I've been enjoying microdot for some time.
Today I've tried implementing an existing project on a generic ESP32 with an Ethernet interface.
As soon as I get to:
```
async def main():
    await app.start_server(host='0.0.0.0', port=80, debug=True)

```
The Ethernet interface stops responding to ICMP ping.

As a quick test I configured the wifi interface and microdot happily serves over that:
```
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4344
load:0x40078000,len:13816
load:0x40080400,len:3340
entry 0x40080618
Wifi Config ('10.4.0.78', '255.192.0.0', '10.0.1.254', '10.0.0.1')
RGBW order selected
Config: ('10.4.0.170', '255.192.0.0', '10.0.1.254', '10.0.0.1')  <--- ETHERNET
CREATE TASK main - this starts the WebServer
CREATE TASK monitor - this is the watchdog
CREATE TASK roll - this drives the NeoPixels
CREATE TASK buttons - this listens to the Buttons
Starting async server on 0.0.0.0:80...
GET / 200
GET /style.css 200
GET /favicon.ico 200
```

Is there anywhere I should be looking?

Regards

Andy

**Comment by miguelgrinberg** [comment]
I'm not sure. Microdot does not do anything that is specific to WiFi. Is your Ethernet interface compatible with the network stack in MicroPython? If it requires a custom library then you'll need to make modifications to Microdot, I suppose.
