### ISSUE TITLE
HTML Templates

### ISSUE THREAD

**Issue by RodriguesBruno** [miguelgrinberg/microdot#46]
Hello Miguel, I've come across with your project and I was wondering if you are considering adding template system (jinja2) to it.
Thank you

**Comment by miguelgrinberg** [comment]
The problem is that Jinja will not work with MicroPython, which is the platform most people use Microdot on. If you are using CPython you should be able to add Jinja and use it directly, in the same way you can use utemplate if you are on MicroPython.

**Comment by RodriguesBruno** [comment]
I'm also using on microPython but I was not sure if Jinja was supported on it.
Thanks for confirming that Miguel.
