### ISSUE TITLE
Question: run asgi and wsgi app

### ISSUE THREAD

**Issue by yuanyanhui** [miguelgrinberg/microdot#47]
Are the two examples supposed to be run on a computer os terminal? To run on ESP32, do I need to  upip install uvicorn and gunicorn, and run the app in Python code?

**Comment by miguelgrinberg** [comment]
There are no ASGI or WSGI web servers for MicroPython, at least none that I know. These are examples that can only run on CPython.

**Comment by yuanyanhui** [comment]
I searched a little and found nothing either. Thanks for making this clear.
