### ISSUE TITLE
[Pico W] CircuitPython support vs. switching to MicroPython

### ISSUE THREAD

**Issue by sgbaird** [miguelgrinberg/microdot#51]
I built up a [basic Pico W - compatible example for an autonomous research lab demo](https://github.com/sparks-baird/self-driving-lab-demo/tree/main/scripts/pico-w) using CircuitPython libraries like [`neopixel`](https://github.com/adafruit/Adafruit_NeoPixel) and [`adafruit_as7341`](https://github.com/adafruit/Adafruit_AS7341). If I want to use microdot, seems I'll need to switch over to running MicroPython and then [use the Blinka compatibility layer to access the CircuitPython libs](https://learn.adafruit.com/circuitpython-libraries-on-micropython-using-the-raspberry-pi-pico) (and hope that what I want is supported). Does that seem like the best option? Any feedback/suggestions?

The alternative I've been trying to avoid is asking users to [parse through web server setup code](https://www.raspberrypi.com/news/how-to-run-a-webserver-on-raspberry-pi-pico-w/) that they'll likely have very little familiarity with. Flask came to mind, but it was quickly obvious that it's not suited for Pico. Then came across [a YouTube comment about microdot](https://www.youtube.com/watch?v=AK8UYh7pMGM).

**Comment by miguelgrinberg** [comment]
Is there anything in this package that is incompatible with CircuitPython? The language is always MicroPython. As long as the low level socket support exists, Microdot should run fine.

**Comment by sgbaird** [comment]
@miguelgrinberg thanks, turns out it's an issue of CircuitPython not supporting Pico W yet https://github.com/adafruit/circuitpython/issues/6558. So, I'll need to set it up per MicroPython's instructions.
