### ISSUE TITLE
[FEATURE REQUEST] example of controlling an LED and reading temperature from Pico W

### ISSUE THREAD

**Issue by sgbaird** [miguelgrinberg/microdot#52]
Sort of an IoT "Hello, World!" example using microdot and Pico W, similar to:
- https://www.raspberrypi.com/news/how-to-run-a-webserver-on-raspberry-pi-pico-w/
- https://github.com/recantha/PicoTemp
- https://www.tomshardware.com/how-to/send-and-receive-data-raspberry-pi-pico-w-mqtt
- https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf
- etc.

It seems like the code could be a lot more succinct using Microdot.

**Comment by sgbaird** [comment]
Just noticed the [GPIO example](https://github.com/miguelgrinberg/microdot/blob/main/examples/gpio/gpio.py).

**Comment by miguelgrinberg** [comment]
Yeah, I'm not sure there is a need to have examples for specific boards. There are just too many.

**Comment by sgbaird** [comment]
All good! Thanks for the quick responses.
