### ISSUE TITLE
problème update V1 tout V1.1

### ISSUE THREAD

**Issue by sophiedegran** [miguelgrinberg/microdot#61]
Miguel
Many thanks with that fantastic project
There is a problem on microdotwebsocket.py with 
self.request.sock.write line 20 and after you are not writing self.request.sock.send
Same thing with self.request.sock.read line 113 and after it is self.request.sock.recv

Regards

**Comment by miguelgrinberg** [comment]
Yes, I have been testing almost exclusively with a TLS web server and did not realize that I left an inconsistency between that and the regular non-encrypted server. Please retest with version 1.1.1 and let me know if the problem is addressed.

**Comment by sophiedegran** [comment]
sending json data every 15sec and works like a charm

Thanks



Le dim. 18 sept. 2022 12:19, Miguel Grinberg ***@***.***> a
écrit :
