### ISSUE TITLE
utemplate and pico w

### ISSUE THREAD

**Issue by diegorebollo** [miguelgrinberg/microdot#66]
Hi!, I'm trying to use utemplate implementation but for whatever reason it didn't work, and i don´t understand why. Any clue?

![Screenshot from 2022-10-01 22-04-16](https://user-images.githubusercontent.com/111189622/193426977-4ff92dc6-4395-4a7d-b198-551eea0d6162.png)

**Comment by miguelgrinberg** [comment]
Try putting your html template in a templates subdirectory.

**Comment by diegorebollo** [comment]
Okay, it was that simple thing. Thank you very much!.
