### ISSUE TITLE
post upload 413

### ISSUE THREAD

**Issue by sophiedegran** [miguelgrinberg/microdot#78]
Many tks miguel for this fantastic project

Trying to use your upload example it works fine with 12ko jpg file but exceed 15  or 16ko server send 413
(Payload too large) and in javascript console Error connexion reset (normal)

Client windows 10, edge 92.x

regards

**Comment by miguelgrinberg** [comment]
This is a security feature. You can configure a different maximum allowed request size. See https://microdot.readthedocs.io/en/latest/api.html#microdot.Request.max_body_length in the documentation.

**Comment by sophiedegran** [comment]
You're right and also max content length

It works like a charm
Thanks
