### ISSUE TITLE
having issues setting up a route

### ISSUE THREAD

**Issue by codiak6335** [miguelgrinberg/microdot#81]
I hope this is user error... but trying to create a route for "change" and it always 404's when called

@app.route('/change', methods=['GET', 'POST'])
def change(request):
     print (request.args)
    return send_file('Interval.html')

http://192.168.0.134:5000/change?time=11&recaptchaResponse=

**Comment by miguelgrinberg** [comment]
The problem must be somewhere else, not in the code that you are showing me. What else do you have in your application? Is it a single file? Multiple files? What's the structure?

**Comment by codiak6335** [comment]
Looks like it was user error and I still don't know where...  but in stripping my code to post, I actually got it to work.   Thanks for the followup and sorry for wasting your time.
